# Fly.io configuration file
app = "brewtracker-backend"
primary_region = "lhr"

[build]

[env]
  FLASK_ENV = "production"
  PORT = "5000"
  HOST = "0.0.0.0"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[vm.http_service.concurrency]]
  type = "connections"
  hard_limit = 100
  soft_limit = 80

