"""Initial migration

Revision ID: 5448451cbc47
Revises: 
Create Date: 2025-04-29 16:52:04.022395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5448451cbc47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('recipes',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('batch_size', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('parent_recipe_id', sa.Integer(), nullable=True),
    sa.Column('estimated_og', sa.Float(), nullable=True),
    sa.Column('estimated_fg', sa.Float(), nullable=True),
    sa.Column('estimated_abv', sa.Float(), nullable=True),
    sa.Column('estimated_ibu', sa.Float(), nullable=True),
    sa.Column('estimated_srm', sa.Float(), nullable=True),
    sa.Column('boil_time', sa.Integer(), nullable=True),
    sa.Column('efficiency', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_recipe_id'], ['recipes.recipe_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_table('brew_sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brew_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mash_temp', sa.Float(), nullable=True),
    sa.Column('actual_og', sa.Float(), nullable=True),
    sa.Column('actual_fg', sa.Float(), nullable=True),
    sa.Column('actual_abv', sa.Float(), nullable=True),
    sa.Column('actual_efficiency', sa.Float(), nullable=True),
    sa.Column('fermentation_start_date', sa.Date(), nullable=True),
    sa.Column('fermentation_end_date', sa.Date(), nullable=True),
    sa.Column('packaging_date', sa.Date(), nullable=True),
    sa.Column('tasting_notes', sa.Text(), nullable=True),
    sa.Column('batch_rating', sa.Integer(), nullable=True),
    sa.Column('photos_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.recipe_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brew_sessions')
    op.drop_table('recipes')
    op.drop_table('users')
    # ### end Alembic commands ###
