name: Deploy Backend to Fly.io

on:
  push:
    branches: [main]
    paths: ['backend/**']
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    
    # Only run if backend files changed
    if: contains(github.event.head_commit.modified, 'backend/') || contains(github.event.head_commit.added, 'backend/') || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        working-directory: ./backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Health Check
        run: |
          sleep 30
          curl -f https://brewtracker-backend.fly.dev/api/health || exit 1
        
      - name: Notify Success
        if: success()
        run: echo "✅ Backend deployed successfully to https://brewtracker-backend.fly.dev"
        
      - name: Notify Failure
        if: failure()
        run: echo "❌ Backend deployment failed. Check logs above."